### PR TITLE
Breaking up structure and formatting of home page

### PR DESCRIPTION
**Pull request by daniellegaither**
Suggested breaking up the salient points into different sections (Upcoming Events, About WWC, About Denton, etc.)

### CODE REVIEW

**Comment by daniellegaither** [comment]
Set up table for upcoming events

**Comment by daniellegaither** [comment]
Adding Morrison's photo

**Comment by daniellegaither** [comment]
Added Leadership page. I think it helps to put human faces to an organization. The bios are in no way meant to be taken seriously, but I thought the structure might serve as a starting point.

**Comment by daniellegaither** [comment]
Closing this one to break up as originally intended.

**Comment by PopularDemand** [comment]
Thanks @daniellegaither!

**Pull request closed without merging**
